version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: N3rdygamerbr@123
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
